version: '3'
services:
  influxdb:
    image: influxdb:1.7.8
    container_name: surface_analysis_influx
    restart: always
    ports:
      - 8086:8086
    volumes:
      # Mount for influxdb data directory
      - /ssd/influx_data/:/var/lib/influxdb
      # Mount for influxdb configuration
      - /ssd/influx_config/:/etc/influxdb
  grafana:
    image: grafana/grafana:6.5.2-ubuntu
    container_name: surface_analysis_dashboard
    restart: always
    ports:
      - 3000:3000
    volumes:
      # Data persistency
      - /ssd/grafana/data:/var/lib/grafana
      - /ssd/grafana/certs:/etc/grafana/certs

